In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Used_Bikes.csv')
df.head()

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [3]:
df.tail()

bike_name    price    city  kms_driven        owner  \
32643     Hero Passion Pro 100cc  39000.0   Delhi     22000.0  First Owner   
32644       TVS Apache RTR 180cc  30000.0  Karnal      6639.0  First Owner   
32645   Bajaj Avenger Street 220  60000.0   Delhi     20373.0  First Owner   
32646  Hero Super Splendor 125cc  15600.0  Jaipur     84186.0  First Owner   
32647         Bajaj Pulsar 150cc  22000.0    Pune     60857.0  First Owner   

        age  power  brand  
32643   4.0  100.0   Hero  
32644   9.0  180.0    TVS  
32645   6.0  220.0  Bajaj  
32646  16.0  125.0   Hero  
32647  13.0  150.0  Bajaj

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   bike_name   32648 non-null  object 
 1   price       32648 non-null  float64
 2   city        32648 non-null  object 
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object 
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object 
dtypes: float64(4), object(4)
memory usage: 2.0+ MB


In [5]:
df.shape

(32648, 8)

In [6]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [7]:
df.duplicated().sum()

np.int64(25324)

In [8]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of                                   bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0 

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [11]:
#df.dropna(inplace=True) if there is a null value then we use this dropna() function to remove null values

In [12]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='object')

In [13]:
df

bike_name     price       city  kms_driven  \
0       TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1              Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0      Delhi       110.0   
3                     TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                    ...       ...        ...         ...   
9362             Hero Hunk Rear Disc 150cc   25000.0      Delhi     48587.0   
9369                   Bajaj Avenger 220cc   35000.0  Bangalore     60000.0   
9370        Harley-Davidson Street 750 ABS  450000.0    Jodhpur      3430.0   
9371                 Bajaj Dominar 400 ABS  139000.0  Hyderabad     21300.0   
9372              Bajaj Avenger Street 220   80000.0  Hyderabad      7127.0   

            owner  age  power            brand  
0     First Owner  3.0  110.0              TVS  
1     First Owner  4.0  350.0    Royal Enfield  
2     First Owner  8.0  675.0          Triumph  
3     First Owner  4.0  180.0              TVS  
4     First Owner  3.0  150.0           Yamaha  
...           ...  ...    ...              ...  
9362  First Owner  8.0  150.0             Hero  
9369  First Owner  9.0  220.0            Bajaj  
9370  First Owner  4.0  750.0  Harley-Davidson  
9371  First Owner  4.0  400.0            Bajaj  
9372  First Owner  5.0  220.0            Bajaj  

[7324 rows x 8 columns]

In [14]:
df['brand'].value_counts()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [15]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [16]:
df['brand'].nunique()

23

In [17]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [18]:
df['owner'].nunique()

4

In [19]:
df['owner'].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [20]:
df.describe()

price     kms_driven          age        power
count  7.324000e+03    7324.000000  7324.000000  7324.000000
mean   8.488390e+04   23910.496587     6.656472   228.133397
std    1.209662e+05   27317.594631     3.605299   158.324219
min    4.400000e+03       1.000000     1.000000   100.000000
25%    3.000000e+04   10155.750000     4.000000   125.000000
50%    5.500000e+04   19000.000000     6.000000   160.000000
75%    1.000000e+05   30112.000000     8.000000   350.000000
max    1.900000e+06  750000.000000    63.000000  1800.000000

In [21]:
df.describe().mean()

price         287821.761805
kms_driven    108477.605152
age              927.032721
power           1280.682202
dtype: float64

In [22]:
Bajaj_brand_df =df[df['brand']=='Bajaj']

In [23]:
first_Bajaj_df = Bajaj_brand_df[Bajaj_brand_df['owner']=="First Owner"]

In [24]:
first_Bajaj_df

bike_name     price       city  kms_driven        owner  \
12          Bajaj Pulsar NS200   78000.0  Bangalore      9900.0  First Owner   
13         Bajaj Discover 100M   29499.0      Delhi     20000.0  First Owner   
14         Bajaj Discover 125M   29900.0      Delhi     20000.0  First Owner   
15      Bajaj Pulsar NS200 ABS   90000.0  Bangalore     11574.0  First Owner   
16      Bajaj Pulsar RS200 ABS  120000.0  Bangalore     23000.0  First Owner   
...                        ...       ...        ...         ...          ...   
9360        Bajaj Pulsar NS200   48000.0  Allahabad     41939.0  First Owner   
9361       Bajaj Avenger 220cc   50000.0  Bangalore     29134.0  First Owner   
9369       Bajaj Avenger 220cc   35000.0  Bangalore     60000.0  First Owner   
9371     Bajaj Dominar 400 ABS  139000.0  Hyderabad     21300.0  First Owner   
9372  Bajaj Avenger Street 220   80000.0  Hyderabad      7127.0  First Owner   

      age  power  brand  
12    4.0  200.0  Bajaj  
13    8.0  100.0  Bajaj  
14    7.0  125.0  Bajaj  
15    3.0  200.0  Bajaj  
16    3.0  200.0  Bajaj  
...   ...    ...    ...  
9360  8.0  200.0  Bajaj  
9361  7.0  220.0  Bajaj  
9369  9.0  220.0  Bajaj  
9371  4.0  400.0  Bajaj  
9372  5.0  220.0  Bajaj  

[1904 rows x 8 columns]

In [25]:
first_Bajaj_df[first_Bajaj_df['kms_driven']<=50000]

bike_name     price       city  kms_driven        owner  \
12          Bajaj Pulsar NS200   78000.0  Bangalore      9900.0  First Owner   
13         Bajaj Discover 100M   29499.0      Delhi     20000.0  First Owner   
14         Bajaj Discover 125M   29900.0      Delhi     20000.0  First Owner   
15      Bajaj Pulsar NS200 ABS   90000.0  Bangalore     11574.0  First Owner   
16      Bajaj Pulsar RS200 ABS  120000.0  Bangalore     23000.0  First Owner   
...                        ...       ...        ...         ...          ...   
9349       Bajaj Pulsar  180cc   55000.0       Pune     10000.0  First Owner   
9360        Bajaj Pulsar NS200   48000.0  Allahabad     41939.0  First Owner   
9361       Bajaj Avenger 220cc   50000.0  Bangalore     29134.0  First Owner   
9371     Bajaj Dominar 400 ABS  139000.0  Hyderabad     21300.0  First Owner   
9372  Bajaj Avenger Street 220   80000.0  Hyderabad      7127.0  First Owner   

      age  power  brand  
12    4.0  200.0  Bajaj  
13    8.0  100.0  Bajaj  
14    7.0  125.0  Bajaj  
15    3.0  200.0  Bajaj  
16    3.0  200.0  Bajaj  
...   ...    ...    ...  
9349  6.0  180.0  Bajaj  
9360  8.0  200.0  Bajaj  
9361  7.0  220.0  Bajaj  
9371  4.0  400.0  Bajaj  
9372  5.0  220.0  Bajaj  

[1718 rows x 8 columns]

In [26]:
#droping unused columns
# 
df.drop(['bike_name','city'],inplace=True, axis = 1)

In [27]:
df

price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [28]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [29]:
dct = {
  'First Owner':1, 'Second Owner':2, 'Third Owner':3,
       'Fourth Owner Or More':4 
}

In [30]:
df['owner']=df['owner'].map(dct)

In [31]:
df

price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [32]:
df['owner'].unique()

array([1, 2, 3, 4])

In [33]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [34]:
brand_dct = {
    'TVS':1, 'Royal Enfield':2, 'Triumph':3, 'Yamaha':4, 'Honda':5, 'Hero':6,
       'Bajaj':7, 'Suzuki':8, 'Benelli':9, 'KTM':10, 'Mahindra':11, 'Kawasaki':12,
       'Ducati':13, 'Hyosung':14, 'Harley-Davidson':15, 'Jawa':16, 'BMW':17, 'Indian':18,
       'Rajdoot':19, 'LML':20, 'Yezdi':21, 'MV':22, 'Ideal':23
}

In [35]:
df['brand']=df['brand'].map(brand_dct)

In [36]:
df

price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      6
9369   35000.0     60000.0      1  9.0  220.0      7
9370  450000.0      3430.0      1  4.0  750.0     15
9371  139000.0     21300.0      1  4.0  400.0      7
9372   80000.0      7127.0      1  5.0  220.0      7

[7324 rows x 6 columns]

In [37]:

x = df.drop('price', axis=1)
y = df[['price']]

In [38]:
x

kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      6
9369     60000.0      1  9.0  220.0      7
9370      3430.0      1  4.0  750.0     15
9371     21300.0      1  4.0  400.0      7
9372      7127.0      1  5.0  220.0      7

[7324 rows x 5 columns]

In [39]:
y

price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
x_train , x_test , y_train , y_test = train_test_split(x,y ,random_state=42, test_size=0.2)

In [42]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((5859, 5), (1465, 5), (5859, 1), (1465, 1))

In [43]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [44]:
lr.fit(x_train, y_train)

LinearRegression()

In [45]:
lr.score(x_train, y_train)

0.7053826605671762

In [46]:
lr.score(x_test, y_test)

0.7586900869386206

In [47]:
lr.predict(x_test)

array([[125382.54523531],
       [216422.20333617],
       [ 96966.48595241],
       ...,
       [ 72233.83615101],
       [208856.67620686],
       [  9305.60087569]], shape=(1465, 1))

In [48]:
#how to save this model and how to use this model
#joblib already install in system

import joblib
#object nm , "model.lb" -------> saved model
model = joblib.dump(lr, "model.lb") 


In [49]:
#using model direclty

model = joblib.load("model.lb")
model.predict(x_test)

array([[125382.54523531],
       [216422.20333617],
       [ 96966.48595241],
       ...,
       [ 72233.83615101],
       [208856.67620686],
       [  9305.60087569]], shape=(1465, 1))

In [50]:
# loss=actual-predeiction
# 4 types - msc,mae,rms,rmse root mean mean square error, 

#suport vector regression

from sklearn.svm import SVR

sv=SVR()

sv.fit(x_test,y_test)
pred= sv.predict(x_test)
pred



C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([53846.46045382, 54001.48617811, 53926.46282884, ...,
       53831.29540272, 53973.18963609, 54001.99298602], shape=(1465,))

In [51]:
sv.score(x_train,y_train)
sv.score(x_test,y_test)



-0.06282721605969344

In [53]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(x_train,y_train)
print(rf.score(x_train,y_train))
print(rf.score(x_test,y_test))
rf.predict(x_test)
# --- IGNORE ---


C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


0.9837483083969748
0.8991943575442723


array([109390.5 , 151676.93,  54125.4 , ...,  50415.  , 104763.73,
        75254.  ], shape=(1465,))

In [2]:
# !pip install xgboost
# import xgboost as xgb
# xg = xgb.XGBRegressor()
# xg.fit(x_train, y_train)
# xg.score(x_train, y_train)
# xg.score(x_test, y_test)
# xg.predict(x_test)
# # --- IGNORE --------> new file




^C


ModuleNotFoundError: No module named 'xgboost'

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/56.8 MB ? eta -:--:--
   ---------------------------------------- 0.5/56.8 MB 5.3 MB/s eta 0:00:11
   - -------------------------------------- 1.6/56.8 MB 4.2 MB/s eta 0:00:14
   - -------------------------------------- 2.4/56.8 MB 4.0 MB/s eta 0:00:14
   -- ------------------------------------- 2.9/56.8 MB 3.9 MB/s eta 0:00:14
   -- ------------------------------------- 3.4/56.8 MB 3.7 MB/s eta 0:00:15
   -- ------------------------------------- 3.7/56.8 MB 3.3 MB/s eta 0:00:17
   -- ------------------------------------- 3.7/56.8 MB 3.3 MB/s eta 0:00:17
   -- ------------------------------------- 3.9/56.8 MB 2.6 MB/s eta 0:00:21
   -- ------------------------------------- 3.9/56.8 MB 2.6 MB/s eta 0:00:21
   -- ------------------------------------- 3.9/56.8 MB 2.6 MB/s eta 0:00:21
   -- ------------------------------------- 4.2/56.8 MB 1.9 MB/s eta 0:00:28
   --