In [ ]:
import numpy as np


In [12]:
arr=np.array([1, 2, 3])
print("array" ,arr)
print("datatype", arr.dtype)
print("type",type(arr))


array [1 2 3]
datatype int64
type <class 'numpy.ndarray'>


In [29]:


arr1=np.arange(20)
print(arr1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [43]:
arr2=np.array([1,2,3,4])
print(arr2)

arr3=np.array([4,5,6,2])
print(arr3)

add=arr2+arr3
print("add",add)

sub=arr2-arr3
print("sub",sub)

mul=arr2*arr3
print("mul",mul)

div=arr2/arr3
print("div",div)



[1 2 3 4]
[4 5 6 2]
add [5 7 9 6]
sub [-3 -3 -3  2]
mul [ 4 10 18  8]
div [0.25 0.4  0.5  2.  ]


In [47]:
print(np.zeros(5))  #float datatype
print(np.ones(5)) #float datatype
print(np.ones(5, dtype=int)) #int datatype

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]


In [56]:
arr4=np.arange(60)
print(arr4, sep="\n")
print(arr4.ndim)
print("shape" ,arr4.shape)
print(arr4.size)
print(arr4.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
1
shape (60,)
60
int64


In [65]:
# 1 d array to 2 d array
arr4=arr4.reshape(6,10)
print(arr4)
print(arr4.ndim)
print("shape" ,arr4.shape)
print(arr4.size==arr4.shape[0]*arr4.shape[1])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
2
shape (6, 10)
True


In [98]:
# indexing and slicing?
# print(arr4[2,3])
# print(arr4[2][3])
# print(arr4[0:5, 0:4])
print(arr4[0:2])
print()
print(arr4[0:2,3])

print("last elemnt)")

print(arr4[-1,-1])
print(arr4[arr4.shape[0]-1, arr4.shape[1]-1])
# print(arr4[:, 3])
print(arr4.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

[ 3 13]
last elemnt)
59
59
(6, 10)


In [ ]:
# i d array to 3 d

arr5=np.arange(120).reshape(2,60)
print(arr5)
print("after ",sep="\n")
arr5=arr5.reshape(2,6,10)
print(arr5)
print(arr5.ndim)


[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
   54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
   96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
  114 115 116 117 118 119]]
after 
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]]

 [[ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 1

In [151]:

arr5=np.arange(6).reshape(2,3)
print(arr5)
print(arr5.shape)
arr5=arr5.T
print(arr5)
print(arr5.shape)



[[0 1 2]
 [3 4 5]]
(2, 3)
[[0 3]
 [1 4]
 [2 5]]
(3, 2)


In [165]:
#3d to 1 d
print(arr5)
print(arr5.shape)

# arr5.flatten() #it flattens the array flatten() creates a new 1D copy of the original array.
print(arr5.flatten())
print(arr5.flatten().shape)

# arr5.ravel() #it flattens the array but it is a view of original array
print(arr5.ravel())  # one return value one dont
print(arr5.ravel().shape)

# ravel() also flattens the array — but it returns a view of the original array (whenever possible).

# # That means changes to this flattened view will also change arr5.
# flatten() → New 1D copy (safe, independent).

# ravel() → 1D view (more memory-efficient, changes reflect).
print()
print()
print()
arr7=np.arange(24).reshape(2,3,4)
print(arr7)
print(arr7.shape)
print(arr7.ndim)
print(arr7.flatten())
print(arr7.flatten().shape)
print(arr7.ravel())
print(arr7.ravel().shape)
arr7=arr7.flatten()[5]

print(arr7)
print(arr7.shape)
print(arr7.ndim)


[[0 3]
 [1 4]
 [2 5]]
(3, 2)
[0 3 1 4 2 5]
(6,)
[0 3 1 4 2 5]
(6,)



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
5
()
0
